include:
  - compose.base.yaml

services:
  dev-nginx:
    image: nginx:1.27-alpine
    environment:
      BIND_IP: 0.0.0.0
      PORT: 8234
    ports:
      - "8234:8234"
    volumes:
      - ../docker/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ..:/usr/share/nginx/html:ro
