services:
  devcontainer:
    image: ${PI_BOX_IMAGE:-morchv/pi-box:latest}
    container_name: ${COMPOSE_PROJECT_NAME}-devcontainer
    hostname: pi-box
    env_file:
      - path: ${PI_BOX_ENV_FILE:-${PI_BOX_ROOT:-~/.pi-box}/pi-box.env}
        required: false
    working_dir: /workspace/${WORKSPACE}
    volumes:
      - "..:/workspace/${WORKSPACE}:z"
      - "${PI_BOX_ROOT:-~/.pi-box}/home:/home/pi:z"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
